### ISSUE TITLE
[Bug]: Maker onboarded hotspot qty seems to have broken

### ISSUE THREAD

**Issue by shawaj** [helium/explorer#622]
### What happened?

The counter on the makers tab seems to have got stuck and has not incremented in some time, despite hotspots being added.

Tried on several devices and browsers and seems to persist on all.

### URL

https://explorer.helium.com/hotspots/makers

### What browsers are you seeing the problem on?

Chrome, Safari, Firefox

### Do you see the issue on Mobile or Desktop?

Mobile, Desktop

**Comment by cokes518** [comment]
looks like we can use the `activity/count` route and look up `add_gateway_v1` and sum `assert_location_v1` and `assert_location_v2` to tabulate quantity 

https://api.helium.io/v1/accounts/13Zni1he7KY9pUmkXMhEhTwfUpL9AcEV1m2UbbvFsrU9QPTMgE3/activity/count

**Comment by cokes518** [comment]
Update: explorer does use those routes, but it updates on a 10 minute interval. However it seems to not be updating consistently so we'll have to look at this in explorer-api 

cc @allenan

**Comment by shawaj** [comment]
It's been stuck for at least ~12 hours or so now I think. Didn't screenshot the exact time but it was around 6am this morning I looked and now 6pm UK time and hasn't changed for any vendor.

**Comment by cokes518** [comment]
I'm not disagreeing that something's wrong.. just that the person that can look is out today.

**Comment by shawaj** [comment]
@cokes518 no didn't think you were disagreeing, just wanted to note roughly how long it had been stuck for was all 🙂

**Comment by cokes518** [comment]
checking in. we're still investigating. we think it's because calchip's maker account's activity feed is returning 404. unfortunately there are larger API issues that needs addressing first.

**Comment by shawaj** [comment]
Thanks @cokes518 for the update

**Comment by esticle** [comment]
The above calchip issue resolved things but now, 24hours later - it appears that maker numbers has remained the same again

**Comment by cokes518** [comment]
this is now fixed.

**Comment by esticle** [comment]
> this is now fixed.

I'm sorry - this is not fixed.

The 'Hotspots added' numbers at https://explorer.helium.com/hotspots/makers has been the same since August 13th.
The 'Hotspots added' numbers at https://explorer-v1.helium.com/hotspots shows numbers that reflect around July 19th

**Comment by cokes518** [comment]
@allenan the data has updated, but still stale.

**Comment by cokes518** [comment]
API is returning 53506 for calchip 
<img width="240" alt="image" src="https://user-images.githubusercontent.com/19331274/129640881-9b0b0ece-eb2a-4d0c-a1e5-40f07edd4777.png">
https://api.helium.io/v1/accounts/13ENbEQPAvytjLnqavnbSAzurhGoCSNkGECMx7eHHDAfEaDirdY/activity/count

Explorer: 
<img width="369" alt="image" src="https://user-images.githubusercontent.com/19331274/129640851-e525baf7-9d2a-4606-9b1a-5c122a3d05e5.png">

**Comment by cokes518** [comment]
This looks like it's *finally* fixed.
